name: Actions Workflow

on:
  # schedule:
  #   - cron: "0/2 5 * * *" #it runs on 2 minutes from 59 seconds

  pull_request:
    types: [closed, assigned, opened, reopened]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: Simple Javascript Action
        id: hello
        uses: actions/hello-world-javascript-action@v1
        with:
          who-to-greet: rahuljoshi

      - name: Get The output time
        run: echo "${{ steps.hello.outputs.time }}"
