name: Custom Environment Variables

on: push

env:
  SUBSCRIBE: Subscribe #this is global enviroment variable avail for all jobs

jobs:
  Subscribe-my-topics:
    runs-on: ubuntu-latest
    env:
      LIKE: Please like share #this is second avail all This Jobs
    steps:
      - name: "Please like share and Subscribe our Devops mania Channel"
        run: echo "This is sample $LIKE and $SUBSCRIBE our $CHANNEL_NAME"

        env:
          CHANNEL_NAME: DevopsMania #this is third avail for this steps particular
