name: matrix
on: push

jobs:
  Node-versions:
    strategy:
      matrix:
        os: [macos-latest, windows-latest, ubuntu-latest]
        node_version: [6, 7, 8]
        exclude:
          - os: ubuntu-latest
            node_version: 7
          - os: windows-latest
            node_version: 7
          - os: macos-latest
            node_version: [6, 7, 8]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Node version
        run: node -v
      - uses: actions/setup-node@v1
        with:
          node-version: 8
      - name: After Setup-node ode version
        run: node -v
